---
- name: Deploy LEMP Stack phpMyAdmin
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    web_root: /usr/share/nginx/html
    db_name: webdb
    db_user: webuser
    db_pass: webpass

  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Check Nginx started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Install PHP
      ansible.builtin.dnf:
        name:
          - php
          - php-fpm
          - php-mysqlnd
        state: present

    - name: Check PHP-FPM is started and enabled
      ansible.builtin.service:
        name: php-fpm
        state: started
        enabled: yes

    - name: Install MariaDB server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: Check MariaDB is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install PyMySQL dependency
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present

    - name: Create database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create DB user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL"
        host: "localhost"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Deploy PHP+HTML template
      ansible.builtin.template:
        src: /etc/ansible/templates/index.php.j2
        dest: "{{ web_root }}/index.php"
        owner: root
        group: root
        mode: '0644'

    - name: Check EPEL is installed
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
        disable_gpg_check: yes
        
    - name: Install phpMyAdmin
      ansible.builtin.dnf:
        name: phpmyadmin
        state: present

    - name: Create symlink phpMyAdmin in web root
      ansible.builtin.file:
        src: /usr/share/phpMyAdmin
        dest: "{{ web_root }}/phpmyadmin"
        state: link

    - name: Deploy Nginx config for PHP
      ansible.builtin.template:
        src: /etc/ansible/templates/default.php.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload nginx
        - Restart php-fpm

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Restart php-fpm
      ansible.builtin.service:
        name: php-fpm
        state: restarted